# Generated by Django 4.1.13 on 2024-05-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TapTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag_name', models.CharField(max_length=50)),
                ('tag_location', models.CharField(max_length=50)),
                ('email_assigned_to', models.CharField(max_length=50)),
                ('intialized', models.CharField(max_length=10)),
            ],
        ),
    ]
